name: CI

on:
  workflow_dispatch:



jobs:
  tests:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: Save binary archive for three days
        uses: actions/upload-artifact@v3
        with:
          name: myartifact
          path: ./myartifact
          retention-days: 3
